// Native gameplay tags used by C++. Data-only tags (buffs, cues, item tags) stay in DefaultGameplayTags.ini.

#pragma once

#include "NativeGameplayTags.h"

namespace MyGameplayTags
{
	MYGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Attacking);
	MYGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Combo_CanCancel);

	MYGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_HitStun);
	MYGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_StunImmune);
	MYGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_NoControl);
	MYGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_NoMove);
	MYGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_NoPawnBlock);
	MYGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_ImmuneProjectile);
	MYGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Health_75);
	MYGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Health_70);
	MYGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Health_50);
	MYGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Health_30);
	MYGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Health_25);

	MYGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Activate_GroundAttack);
	MYGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Activate_FlyingAttack);

	MYGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Notify_Hit_Start);
	MYGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Notify_Hit_End);
	MYGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Notify_Hit_Connect);
	MYGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Notify_Projectile_Cast);

	// Sent to a character to make it dash; GA_Dash triggers on it
	MYGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Dash);

	// Released ability buttons, sent as gameplay events (index = EInput: Punch, Kick, Cast, Jump)
	MYGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Release_0);
	MYGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Release_1);
	MYGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Release_2);
	MYGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Release_3);

	// SetByCaller magnitudes and effect markers read by the hit handling
	MYGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage);
	MYGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_HitStun);
	MYGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Knockback);
	MYGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_CamShake);
	MYGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Launch);
	MYGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Launch_X);
	MYGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Launch_Y);
	MYGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Launch_Z);
	MYGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_NoApply);
	MYGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_StunImmune);
	MYGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_NoControl);
}
